### ISSUE TITLE
Different colors on website

### ISSUE THREAD

**Issue by curratore** [neovasili/devopsdays-web#1]
Actual status:
Different colors on 
Call for Papers, Sponsor, Contact, etc. blocks and Social Networks blocks
![image](https://user-images.githubusercontent.com/1506358/205349270-6af2a130-b756-4948-afec-16827d93d8cc.png)

Desired status:
Same color on both blocks

**Comment by neovasili** [comment]
Disagree, they are different set of Call to action buttons, so they should have different colours, we can switch the colours from one to the other, but I think they should stay different. I choose the stronger colour for the more relevant buttons.

The chosen colours belongs to our already defined UI Kit inside the Drive shared drive: DevOpsDays2023 -> Marketing -> MIC.pdf
